### PR TITLE
View employee list now works. Added a link to the navbar to allow the…

### PR DESCRIPTION
**Pull request by wilkinson4**
… user to view a list of employees

### CODE REVIEW

**Comment by land0o** [comment]
Ticket
https://github.com/nss-day-cohort-34/workforce-management-turkey-induced-coma/issues/1

**Comment by Ellie-Ash** [comment]
looks good to me!

**Review by Ellie-Ash — COMMENTED** [review]
looks good!

**Review by land0o — APPROVED** [review]
👍

**Review by mmjohn09 — APPROVED** [review]
💯

**Pull request merged**
